### PR TITLE
chore: instead of running the whole pipeline again, only allow drafts when main is green already

### PR DESCRIPTION
**Pull request by kmruiz**
### Checklist

- [ ] New tests and/or benchmarks are included.
- [ ] Documentation is changed or added.
- [ ] Changelog is updated accordingly.
- [ ] I have signed the MongoDB Contributor License Agreement (https://www.mongodb.com/legal/contributor-agreement).

### CODE REVIEW

**Comment by himanshusinghs** [comment]
I think its a good idea but there is one thing this might miss, last minute dependency problem creeps (we saw that being quite common in compass repo). Something we should be aware of.

**Comment by kmruiz** [comment]
We are using fixed versions, it shouldn't happen right?

**Comment by himanshusinghs** [comment]
Yea but it might happen that our fixed version was identified for a vuln at some point, right? :D

**Comment by kmruiz** [comment]
Ah true, this might happen for sure. So what we can do is, whenever we generate the SBOM (we are not doing it yet but it's planned), do it also before releasing and after checking main is green. So we don't need to run the whole suite but we verify that our deps don't have any important CVE.

**Review by himanshusinghs — APPROVED** [review]

**Pull request merged**
